// app/constants/config.js

const CONFIG = {
  SCAN_INTERVAL_MS: 15000,
  SYNC_INTERVAL_MS: 10000,
  HEALTH_CHECK_INTERVAL_MS: 30000,
  MAX_MESSAGE_RETRIES: 3,
  GEO_DEFAULT_RADIUS_KM: 30,
  ALERT_CHECK_INTERVAL_MS: 15000,
  MESSAGE_TTL_HOURS: 24,
};

export default CONFIG;

